# Generated by Django 6.0.3 on 2026-03-15 19:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('akce', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='akce',
            name='autor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Autor akce'),
        ),
        migrations.AddField(
            model_name='akce',
            name='upraveno',
            field=models.DateTimeField(auto_now=True, verbose_name='Datum a čas poslední úpravy'),
        ),
    ]
